language: node_js
sudo: required
dist: trusty

node_js:
  - '10.15.3'
branches:
  only:
    - master
    - develop
addons:
  firefox: latest
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
jobs:
  include:
    - if: type = pull_request
      env: 'MODE=commitlint'
    - env: 'MODE=prettier'
    - env: 'MODE=lint'
    - env: 'MODE=aot'
    - env: 'MODE=release'
    - env: 'MODE=unit-test'
    - env: 'MODE=audit'
    - env: 'MODE=a11y'
install:
  - npm ci
script:
  - ./scripts/ci/travis-script.sh
cache:
  directories:
    - ./node_modules/
after_success:
  - test $MODE == "release" && test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "develop" && npm run publish:nightly
